# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LlmStatus < Formula
  desc "TUI dashboard for LLM coding assistant usage"
  homepage "https://github.com/stanacos/llm-status"
  version "0.3.2"

  depends_on "node"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stanacos/llm-status/releases/download/v0.3.2/llm-status_0.3.2_darwin_amd64.tar.gz"
      sha256 "34e3fd40ca48485afa74ae62e3290a0d5aa39e1dbb514df3cafd9b4ff81d12c0"

      define_method(:install) do
        bin.install "llm-status"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stanacos/llm-status/releases/download/v0.3.2/llm-status_0.3.2_darwin_arm64.tar.gz"
      sha256 "3bda463d8b4136030c05029c14f9082bf7cd41e668759adf9afb9a52aff26b13"

      define_method(:install) do
        bin.install "llm-status"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stanacos/llm-status/releases/download/v0.3.2/llm-status_0.3.2_linux_amd64.tar.gz"
      sha256 "8aa1d0b56535c0e4f48e6140b040f4acd966e6638eb191b1ef7031bce8ae988d"
      define_method(:install) do
        bin.install "llm-status"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stanacos/llm-status/releases/download/v0.3.2/llm-status_0.3.2_linux_arm64.tar.gz"
      sha256 "08b2fd54006ab5490adc14a7d6aad779c3deee264297c5120247df8e55653b85"
      define_method(:install) do
        bin.install "llm-status"
      end
    end
  end

  test do
    system "#{bin}/llm-status", "--version"
  end
end
