# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LlmStatus < Formula
  desc "TUI dashboard for LLM coding assistant usage"
  homepage "https://github.com/stanacos/llm-status"
  version "0.2.2"

  depends_on "node"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stanacos/llm-status/releases/download/v0.2.2/llm-status_0.2.2_darwin_amd64.tar.gz"
      sha256 "23407f86eaa8ffd7e5756f99fbefbcac32afc882cb5c63c4d56f2c59f747db62"

      def install
        bin.install "llm-status"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stanacos/llm-status/releases/download/v0.2.2/llm-status_0.2.2_darwin_arm64.tar.gz"
      sha256 "5645742dcae7d1629f71b56afaa93bd0fced1d26deb14699cb493b77a31e84c3"

      def install
        bin.install "llm-status"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stanacos/llm-status/releases/download/v0.2.2/llm-status_0.2.2_linux_amd64.tar.gz"
      sha256 "94c10cc28e76e71d39aa5921f3b99e66c57f728e9648fafa9e93cdedabbe0beb"
      def install
        bin.install "llm-status"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stanacos/llm-status/releases/download/v0.2.2/llm-status_0.2.2_linux_arm64.tar.gz"
      sha256 "c791f26a03f3be38a03d47e2e28a7bb5f1e518ff6b3a6e849bf77c4df15d037a"
      def install
        bin.install "llm-status"
      end
    end
  end

  test do
    system "#{bin}/llm-status", "--version"
  end
end
